# Generated by Django 4.1.5 on 2023-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psicologos', '0004_recomendacion_recomendacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='sector',
            field=models.CharField(choices=[('NO', 'Norte'), ('SU', 'Sur'), ('CE', 'Centro'), ('SA', 'Samborondon'), ('DA', 'Daule')], max_length=2),
        ),
    ]
